services:
  - type: web
    name: telegram-number-bot
    env: python
    region: singapore
    pythonVersion: 3.11
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
